version: '3.8'

services:

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - 1337:80
    depends_on:
      - app

  app:
    build: ./app
    command: gunicorn PilotProject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/app/
      - static_volume:/app/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postresql/data/
    env_file:
      - ./.env.db


volumes:
  postgres_data:
  static_volume: