version: '3.8'

services:

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - 1337:80
    depends_on:
      - app

  app:
    build: ./app
    command: gunicorn PilotProject.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - ./app/:/app/
      - static_volume:/app/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env
      - ./.env.celery.rabbit
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postresql/data/
    env_file:
      - ./.env.db

  rabbitmq3:
#    container_name: rabbitmq
    image: rabbitmq:3.8-management-alpine
    env_file:
      - ./.env.celery.rabbit
    ports:
      # AMQP protocol port
      - 5672:5672
      # HTTP management UI
      - 15672:15672

  celery-beat:
    restart: always
    build: ./app
    container_name: celery-beat
    command: celery -A PilotProject beat --loglevel=DEBUG --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - ./.env
      - ./.env.celery.rabbit
    volumes:
      - ./app/:/app/
    depends_on:
      - db
      - rabbitmq3
      - app

  celery:
    restart: always
    build: ./app
    container_name: celery
    command: celery -A PilotProject worker --loglevel=DEBUG
    env_file:
      - ./.env
      - ./.env.celery.rabbit
    volumes:
      - ./app/:/app/
    depends_on:
      - db
      - rabbitmq3
      - app

volumes:
  postgres_data:
  static_volume: